### ISSUE TITLE
Syncing Accounts: You do not have permission

### ISSUE THREAD

**Issue by matthewkeller36** [Norbit4/DiscordMc#2]
When attempting to sync accounts, I am successfully able to do so on the Discord side. However, attempting to sync, using `/discordmc sync` gives me the error message "You don't have permissions". Is there a line in my config I may be missing? none of the documentations mentions anything about modifying it but I could be wrong.

**Comment by Norbit4** [comment]
You need to add permissions to go your permissions plugin. 

*Command permissions can be found here:* https://github.com/Norbit4/DiscordMc/wiki/Permissions

**Comment by matthewkeller36** [comment]
I see. This is something new to me. Could you give an example of how to configure the YAML file such that one user (or varying levels of users) would be able to execute the different commands? Thank you

**Comment by Norbit4** [comment]
You need a permissions plugin for this, I recommend this one: https://luckperms.net/

tutorial video: https://youtu.be/AwbVqSOn2SI

**Comment by matthewkeller36** [comment]
Thanks! It looks as though that solved the issue. However, attempting to send messages from Discord to the Server seems to be deleting the message and just sending a blank message. Do you know of other reasons that may be happening?

**Comment by Norbit4** [comment]
could you send a screenshot, config.yml and servers logs?

**Comment by DarkForum** [comment]
I have the same, an empty message when I send from Discord

**Comment by DarkForum** [comment]
`#---------------------------------------#
# DiscordMc by Norbit4
# github: https://github.com/Norbit4

#---------------------------------------#
#             [bot config]              #
#---------------------------------------#

# configuration: https://github.com/Norbit4/DiscordMc/wiki/Configuration
enable: true
prefix-command: 'discordmc'
sync-command-arg: 'sync'
sync-command-clear-arg: 'syncclear'
bot-token: 'MY_TOKEN'
bot-activity: ''
discord-server-id: 'MY_DISCORD_ID'

# types: local/mysql/mongodb
database-type: 'local'
host: ''
port: 3306
user: ''
password: ''
database: ''
ssl: false

embed-profile-title: 'Profile'

embed-profile:
  # 'TITLE//DESC'
  - 'Pseudo ://{NICK}'
  - 'Joueur :// {USER}'
  - 'Statut :// {STATUS}'
  - 'World :// {WORLD}'
  - 'Localisation :// X: {X} Y: {Y} Z: {Z}'
  - 'Skin MC :// {NAME_MC}'

# discord rank sync
sync-rank-enable: true
# discord name sync (set discord user mc name)
# this option need enabled 'sync-rank-enabled'
# nick sync does not work for the discord server owner, it is specific to discord servers!
sync-name: false

# wiki sync roles: https://github.com/Norbit4/DiscordMc/wiki/Rank-sync
sync-roles:
  - 'rank.owner:ID'
  - 'rank.default:ID'

namemc-non-premium: 'Le joueur n est pas premium'
player-offline-status: 'Déconnecté'
player-online-status: 'Connecté'
user-in-not-sync: 'Vous n êtes pas synchronisé ! Utilises **/sync** pour synchroniser vos comptes !'
arg-user-in-not-sync: 'Cet utilisateur n est pas synchronisé !'
embed-profile-rgb:
  - 154
  - 199
  - 50

#---------------------------------------#
#              [messages]               #
#---------------------------------------#

# discord embeds colors
warn-message-tittle: 'ATTENTION'
warn-message-rgb:
  #R
  - 213
  #G
  - 156
  #B
  - 71

success-message-tittle: 'SUCCÈS'
success-message-rgb:
  - 26
  - 154
  - 74

error-message-tittle: 'ERREUR'
error-message-rgb:
  - 194
  - 50
  - 50

#discord messages
player-is-sync: 'Ce joueur est synchronisé !'
discord-user-is-sync: 'Tu es synchronisé !'
offline-player: 'Ce joueur est déconnecté !'
sync-info: 'Tapez **/{PREFIX} {ARG1}** dans le chat minecraft pour synchroniser vos comptes !'
sync-success: 'Le joueur **{PLAYER}** a été synchronisé avec le compte : **{DISCORD}**!'

#minecraft messages
permission-message: '&cVous n avez pas les permissions !'
sync-info-mc: '&7Tapez &8/&b{PREFIX} {ARG1} &7pour connecter votre compte avec&a {DISCORD}'
sync-success-mc: '&aSuccess! &7Le compte a été synchronisé avec &c{DISCORD}!'
sync-clear-mc: '&aSuccess! &7La synchronisation a été effacée !'
sync-time-out: '&7Vous n avez pas de synchronisation en attente !'

wrong-args-message: '&7Utilise : &8/&b{PREFIX} &a{ARG1} &8<&a{ARG2}&8>'

command-args-list:
  - '&7------------&8[{PREFIX}&8]------------'
  - ''
  - '&8/&b{PREFIX} &a{SYNC_CMD} &7- accepter les comptes de synchronisation'
  - '&8/&b{PREFIX} &a{SYNC_CLEAR_CMD} &7- effacer votre synchronisation'
  - '&8/&b{PREFIX} &a{CHANNEL_CMD} &8<&a{CHANNEL_MC_ARG}/{CHANNEL_DC_ARG}&8> &7- changer de canal de discussion'
  - '&8/&b{PREFIX} &arankreload &7- recharger le classement synchronisé'
  - '&8/&b{PREFIX} &areload &7- recharger config.yml'
  - ''

#---------------------------------------#
#         [discord-chat-module]         #
#---------------------------------------#
# help: https://github.com/Norbit4/DiscordMc/wiki/Chat-module

discord-chat-module: true
channel-chat-id: 'ID_CHANNEL'

# command
command-chat-change-arg: 'canal'
minecraft-chat-arg: 'mc'
discord-chat-arg: 'dc'
channel-change-message: '&7Le canal a été remplacé par : &a{CHANNEL}'

# minecraft server chat
discord-prefix: '&d[DC] '
mc-prefix: '&a[MC] '
message-mark: '&7: '
message-color: '&7'
nick-color: '&f'

# discord channel chat
discord-message-mark: ': '

# embeds color
discord-user-rgb:
  - 142
  - 87
  - 178

mc-user-rgb:
  - 33
  - 241
  - 99

#---------------------------------------#
#        [discord-console-module]       #
#---------------------------------------#
# help: https://github:com/Norbit4/DiscordMc/wiki/Console-module

discord-console-module: true
channel-console-id: 'ID_CHANNEL'

#allowed commands in discord console
discord-console-commands: true

#allowed to display info discord console
discord-console-display: true

block-error-messages: false

# blocked commands in discord console
blocked-commands:
  - help
  - pl

#---------------------------------------#
#         [discord-info-module]         #
#---------------------------------------#
# help: https://github.com/Norbit4/DiscordMc/wiki/Info-module

discord-info-module: true
channel-info-id: 'ID_CHANNEL'

# message info reload time in seconds, min time: 20s (for safe)
message-reload-time: 30

discord-info-rgb:
  - 26
  - 154
  - 74

# folders ignored when creating worlds list
ignore-folders:
  - 'cache'
  - 'plugins'
  - 'logs'
  - 'crash-reports'
  - 'libraries'
  - 'config'
  - 'versions'

# Placeholders:
# {SERVER_ONLINE}, {SERVER_MAX_PLAYERS}, {SERVER_TIME}, {SERVER_ALL_PLAYERS}, {SERVER_WORLDS}, {SERVER_VERSION},
# {SERVER_ALLOW_NETHER}, {SERVER_ALLOW_END}
#
# PlaceholderAPI support: https://github.com/Norbit4/DiscordMc/wiki/PlaceholderApi-support
embed-tittle: ''
embed-desc: ''
embed-info:
  # 'TITLE//DESC'
  - 'Connecté ://{SERVER_ONLINE}/{SERVER_MAX_PLAYERS}'
  - 'Serveur ouvert depuis :// {SERVER_TIME}'
  - 'All Players :// {SERVER_ALL_PLAYERS}'
  - 'Worlds :// {SERVER_WORLDS}'
  - 'Ver :// {SERVER_VERSION}'
  - 'Nether :// {SERVER_ALLOW_NETHER}'
  - 'End :// {SERVER_ALLOW_END}'

false-info: 'false'
true-info: 'true'`

**Comment by Norbit4** [comment]
what server version are you using?

**Comment by Norbit4** [comment]
.
